##===- projects/loop_unroll/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=loop_unroll

include $(LEVEL)/Makefile.common
