##===- projects/loop_unroll/tools/loop_unroll/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LOADABLE_MODULE=1
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=loop_unroll

#
# List libraries that we'll need
# We use LIBS because loop_unroll is a dynamic library.
#
USEDLIBS = loop_unroll.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

