### Targets ###################################################################

# automatically select most recently modified .tex file
TARGET      := $(basename $(shell ls -t *.tex | head -n1))
TEXFILE     := $(TARGET).tex
PDFFILE     := $(TARGET).pdf

# parse out bib filename
BIBFILE     := $(shell sed -n 's/.*\\bibliography{\([^}]*\)}.*/\1/p' $(TEXFILE) ).bib

# parse out the figures and construction their filenames
FIGDIR      := $(shell sed -n 's/\\graphicspath{{\([^}]*\)}}/\1/p' $(TEXFILE))
FIGFILES    := $(shell sed -n 's/.*\\includegraphics[^{]*{\([^}]*\)}.*/\1/p' $(TEXFILE) | sed 's/\.eps$$//')
EPSFILES    := $(FIGFILES:%=$(FIGDIR)/%.eps)

gui : $(PDFFILE)
	nohup evince $< > /dev/null 2>&1 &

pdf : $(PDFFILE)

eps : $(EPSFILES)

debug :
	@echo TARGET=$(TARGET)
	@echo TEXFILE=$(TEXFILE)
	@echo PDFFILE=$(PDFFILE)
	@echo BIBFILE=$(BIBFILE)
	@echo FIGDIR=$(FIGDIR)
	@echo FIGFILES=$(FIGFILES)
	@echo EPSFILES=$(EPSFILES)


### Dependencies ##############################################################

# with bibliography
LATEX_OPT := -halt-on-error -file-line-error
%.dvi : %.tex $(BIBFILE) $(EPSFILES)
	pdflatex  $(LATEX_OPT) $*
	echo $(BIBFILE)
	bibtex $(TARGET).aux
	pdflatex  $(LATEX_OPT) $*
	pdflatex  $(LATEX_OPT) $*
	rm -vf $*.aux $*.bbl $*.blg $*.log


%.pdf	: %.dvi
	sed -i -e 's/%%Title: .*/%%Title:/' $<  # strip titles

%.eps : %.ps
	ps2eps -f $<
	rm -vf $<

%.ps : %.vsd
	@echo "Oh noez! $< is out of date, convert it to .ps using M$$ Visio"
	@false

%.eps : %.vsd
	@echo "Oh noez! $< is out of date, convert it to .ps using M$$ Visio"
	@false

%.eps :
	@echo "Oh noez! I can't find any files for figure $@"
	@false

### Housekeeping ##############################################################
clean :
	rm -vf *.ps *.dvi *.log *.aux *.out *.blg *.bbl *.d $(PDFFILE)

.PHONY : clean pdf gui
