##===- projects/loop_unroll/lib/loop_unroll/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LOADABLE_MODULE=1
LEVEL=../..

#
# Give the name of a library.  This will build a dynamic version.
#
LIBRARYNAME=loop_unroll

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
